Review: Reviewed Work To Understand Features
I have reviewed the work and verified that models instantiation are ok. Nevertheless, the reload() function that loads json dictionary to a class instance has a few bugs.

error: self.__objects[key] = getattr(models, new_obj[key]['__class__'])(**new_obj[key])
AttributeError: partially initialized module 'models' has no attribute 'BaseModel' (most likely due to a circular import)